name: Vue

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      #6. Always have this line; It contains the run instructions for the below steps
      - uses: actions/setup-node@master
      #7. The above line will set up NodeJS (the latest version ) because we are deploying a VueJS project.
      - run: cd ./vue && npm install
      - run: cd ./vue && npm run build
      - name: Sync
        env:
          dest: "ubuntu@3.104.79.107:/home/ubuntu/belajar-vue.kelasdevops.xyz/"
        run: |
          echo "${{secrets.DEPLOY_KEY}}" > ~/deploy_key
          chmod 600 ~/deploy_key
          rsync -chav --delete \
            -e 'ssh -i ~/deploy_key -o StrictHostKeyChecking=no' \
            --exclude ~/deploy_key \
            --exclude .git/ \
            --exclude .github/ \
            ./vue/dist/ ${{env.dest}}
